on:
  push:
    branches:    
      - master
      
name: Build and Publish Averment
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.averment.com
        username: averment
        password: ${{ secrets.ftp_password }}    