on:
  push:
    branches:    
      - master
      
name: Build and Publish Averment
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      
      with:
        server: 172.32.1.10
        username: maliasili
        password: ${{ secrets.ftp_password }}    